version: '{branch}-{build}'
build: false
shallow_clone: false
platform: x64
clone_folder: c:\projects\phpspec-code-coverage
pull_requests:
  do_not_increment_build_number: true

environment:
  COMPOSER_ROOT_VERSION: '7.0-dev'
  matrix:
    - PHP_VERSION: '7.2.0-Win32-VC15-x86'
      DEPENDENCIES: ''
      XDEBUG_VERSION: '2.6.0-7.2-vc15'
    - PHP_VERSION: '7.2.0-Win32-VC15-x86'
      DEPENDENCIES: '--prefer-lowest'
      XDEBUG_VERSION: '2.6.0-7.2-vc15'
    - PHP_VERSION: '7.1.12-Win32-VC14-x86'
      DEPENDENCIES: ''
      XDEBUG_VERSION: '2.6.0-7.1-vc14'
    - PHP_VERSION: '7.1.12-Win32-VC14-x86'
      DEPENDENCIES: '--prefer-lowest'
      XDEBUG_VERSION: '2.6.0-7.1-vc14'

matrix:
  fast_finish: true

#branches:
  #only:
    #- master

skip_commits:
  message: /\[ci skip\]/

cache:
  - c:\php -> appveyor.yml
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=c:\php\%PHP_VERSION%;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)
  - git config --global core.autocrlf input

install:
  - IF NOT EXIST c:\php mkdir c:\php
  - IF NOT EXIST c:\php\%PHP_VERSION% mkdir c:\php\%PHP_VERSION%
  - cd c:\php\%PHP_VERSION%
  - IF NOT EXIST php-installed.txt curl -fsS -o php-%PHP_VERSION%.zip  https://windows.php.net/downloads/releases/archives/php-%PHP_VERSION%.zip
  - IF NOT EXIST php-installed.txt 7z x php-%PHP_VERSION%.zip -y >nul
  - IF NOT EXIST php-installed.txt del /Q *.zip
  - IF NOT EXIST php-installed.txt copy /Y php.ini-development php.ini
  - IF NOT EXIST php-installed.txt echo max_execution_time=1200 >> php.ini
  - IF NOT EXIST php-installed.txt echo date.timezone="UTC" >> php.ini
  - IF NOT EXIST php-installed.txt echo extension_dir=ext >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_curl.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_openssl.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_mbstring.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_fileinfo.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_mysqli.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_pdo_sqlite.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo zend.assertions=1 >> php.ini
  - IF NOT EXIST php-installed.txt echo assert.exception=On >> php.ini
  - IF NOT EXIST php-installed.txt appveyor DownloadFile https://getcomposer.org/composer.phar
  - IF NOT EXIST php-installed.txt echo @php %%~dp0composer.phar %%* > composer.bat
  - IF NOT EXIST php-installed.txt type nul >> php-installed.txt
  - IF %PHP%==1 appveyor DownloadFile https://xdebug.org/files/php_xdebug-%XDEBUG_VERSION%.dll
  - mv php_xdebug-%XDEBUG_VERSION%.dll ext\
  - echo zend_extension="php_xdebug-%XDEBUG_VERSION%.dll" >> php.ini
  - echo xdebug.remote_enable=true >> php.ini
  - echo xdebug.remote_autostart=true >> php.ini
  - cd c:\projects\phpspec-code-coverage
  - IF NOT EXIST build\coverage mkdir build\coverage
  - composer self-update
  - composer update --no-progress --no-ansi --no-interaction --no-suggest --optimize-autoloader --prefer-stable %DEPENDENCIES%

test_script:
  - cd c:\projects\phpspec-code-coverage
  - bin\phpcs
  - phpdbg -qrr vendor\phpspec\phpspec\bin\phpspec run --no-code-generation -vvv

